# ======================================================
# Production 환경 설정 (application-prod.yml)
# ======================================================

logging:
  level:
    root: WARN


spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}        # ← 환경변수로
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # none, validation(권장)
    show-sql: false
    open-in-view: false